
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: yolo
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@venkatamutyala.com
      PGADMIN_DEFAULT_PASSWORD: yolo
    ports:
      - "8080:80"
    # depends_on:
    #   - db
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
volumes:
  pgdata: